CREATE TABLE IF NOT EXISTS settings (
  key VARCHAR PRIMARY KEY,
  value JSON NOT NULL,
  version VARCHAR NOT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS signals (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ticker VARCHAR NOT NULL,
  signal_date DATE NOT NULL,
  score REAL NOT NULL,
  rank INTEGER NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(ticker, signal_date)
);

CREATE TABLE IF NOT EXISTS trades (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ticker VARCHAR NOT NULL,
  side VARCHAR NOT NULL,
  qty INTEGER NOT NULL,
  price DECIMAL(18,4) NOT NULL,
  executed_at TIMESTAMP NOT NULL,
  pnl DECIMAL(18,4),
  is_paper BOOLEAN NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS portfolio (
  as_of_date DATE PRIMARY KEY,
  equity DECIMAL(18,4) NOT NULL,
  cash DECIMAL(18,4) NOT NULL,
  positions JSON NOT NULL,
  drawdown_pct REAL NOT NULL
);

CREATE TABLE IF NOT EXISTS logs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  ts TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  level VARCHAR NOT NULL,
  source VARCHAR NOT NULL,
  message TEXT NOT NULL
);
